version: '3'
services:
    node:
        networks:
            - net
        image: yuriysga/docker-basics-express:yuriysga
        ports:
            - ${PORT}:${PORT}
        depends_on: 
            - postgres
        environment: 
            - PORT=4000
        restart: always
        volumes:
            - ./src:/usr/app/src
            - ./logs:/usr/app/logs
    postgres:
        image: yuriysga/docker-basics-postgres:yuriysga
        networks:
            - net
        ports: 
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment:
            POSTGRES_HOST: ${P_HOST}
            POSTGRES_PORT: ${P_PORT}
            POSTGRES_USER: ${P_USER}
            POSTGRES_PASSWORD: ${P_PASSWORD}
            POSTGRES_DB: ${P_DB}
        restart: always
        volumes:
            - ./database/postgres-data:/var/lib/postgresql/data
networks:
    net:
        driver: bridge

