version: '3'
services:
  node:
    networks:
      - net
    image: yuriysga/docker-express-typeorm:yuriysga
    ports:
      - ${PORT}:${PORT}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=4000
    restart: always
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
  postgres:
    image: yuriysga/docker-postgres:yuriysga
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net
    ports:
      - ${P_PORT}:${P_PORT}
    environment:
      POSTGRES_USER: ${P_USER}
      POSTGRES_PASSWORD: ${P_PASSWORD}
      POSTGRES_DB: ${P_DB}
    restart: always
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
networks:
  net:
    driver: bridge
